### ISSUE TITLE
Roadmap module 6

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/MCL-programming-in-python#39]
### Content
1. Reminder of DRY principle & more on writing functions 
  - Why we write functions (answer - to dry out our code) (test via MCQ)
  - Scoping (e.g., if x is defined outside the function, and then inside the function, which value for x is used) (test via MCQ showing pictures of function and asking what the value of x would be after running the code and inside the function)
  - Functions should return something (most of the time) and usually do just one thing (test via MCQ)
  - What are function side effects, and when are they useful (e.g., writing things to disc, such as figs & data) (test via matching function to label of side effect producing function or object returning function)

2. Keyword arguments
  - default values for function arguments (that this is possible and how you do this syntactically) (test - get them to edit a function where a value is defined within the function to become a function that instead has a default arg)
  - function argument ordering and default/optional arguments (how this impacts how you call the function, i.e., how does order of calling arguments influence when you have to provide their names when calling the function) (test via MCQ where you show them a function and several possible ways you could call it correctly (i.e., all args in order with no arg names, all out of order with arg names, a mix of both) and one way that would break it. They need to id which is incorrect).

3. Docstrings
  - Writing good docs helps out your most important collaborator - you in 6 months time!
  - Docstrings let you generate help docs which you can access via ?<FUNCTION_NAME> (test via MCQ on how they can access the docs inside Python - this is review but a good reminder) (another test via giving them a function and an explanation of what it does, and they have to add docstrings)
  - show them restructured text formatted docstring, ask them to extract some info. (test via MCQ)
  - show them numpy-style docstrings, , ask them to extract some info. (test via MCQ)
  - ask which is more readable to the developer? (test via MCQ)
  - show how to write docstrings when there are default args (test this by showing function with default arg & docstrings that are correct, and the docs for this are missing the docs for the default, ask them to identify the correct docs? Or you could go the other way around, have several examples where the docs are wrong, and for each case they need to ID what is wrong, you test this via MCQ)

4. Defensive programming via exceptions - when things go wrong, your function should fail fast and early. Handle exceptions where you can.
  - What do exceptions do?
  - Why raise exceptions, and why include useful/helpful error messages
  - What kind of things might one write exceptions for?
(test via giving code for a function, along with docstrings and have users add exceptions to it, as directed by you - for example it's a function that does something to strings, get them to check the function input is a string, if not, throw and exception with a useful message)
(test via giving code for a function, along with docstrings and ask them to add exceptions where they think they should go? Or make a MCQ out of this)

5. Unit tests, corner cases
- intro to assert statements (get them to fill in missing part of assert statements, some cases the logical, but provide the text, other cases provide the text and they need to fill in the logical) 
- Introduce systematic program design (see Mike's description in [this lecture](https://github.ubc.ca/MDS-2020-21/DSCI_511_py-prog_instructors/blob/master/lectures/lecture2.ipynb)) (test via jumbling the order of these steps and asking the students to correct the order)
- What to test (simple examples you know to be true, or could calculate by hand) (test by providing a function stub, such as a function to calculate the mean, and through MCQ ask them to identify a good test - good example would be a `[2, 4, 6]`, poor examples would be `[2.3, 4.5, 6.9]`, using another function to calculate the mean, using far too many numbers) 
- Other good things to test (corner cases and throwing errors when it should) (test via MCQ's similar to above)
- how to write tests for functions that work on data (e.g., make small helper data frames and use these in the tests, the data they create should be small enough to manually work out the answer) (test via giving a function, helper data and part of an assert, have them fill in part of the assert where it calls the helper data)
(test via giving them a function and an assert statement, ask them to create the helper data to make the test pass)

6. Abstracting functions and tests to other files
 - to keep things organized, and to allow us to easily reuse our functions in other projects/analysis it is good to abstract our functions to another file. We similarly do this with our tests. We also usually group our asserts into test functions that are named `test_FUNCTION_NAME`. 
- show them how to import and use functions from another file (test via getting them to use such a function, and a MCQ about why we do this)
- show them where tests should go (test directory) and how to import functions into the tests directory for testing. 
- show them how to run the test file via Pytest at the Jupyter command line?
- all of this testing stuff might need to be demo'ed in a video?  And then assessed in the content via MCQ. More detailed assessment can happen in the assignment.

Things to potentially still add:
- anonymous functions? Maybe add this only if we teach map, and if so, teach it then?
- returning multiple things (not too necessary IMHO)

**Comment by ttimbers** [comment]
A couple notes/thoughts:
- Maybe use the palmer penguin data for this module (assuming you are looking for a new dataset?)
- As much as possible we should try to use authentic function examples (i.e., ones that handle data).

**Comment by ttimbers** [comment]
## Assignment sketch:

1a. Write a function that filters rows (matching an exact value) and selects columns (those are the function inputs) and returns a data frame. Function args include a data frame, condition to filter on (matching an exact value), col name to select.

1b. Write a function that randomly samples N observations from each group in a data frame. Function args include N for the number of observations to sample and the grouping column. This function should have a default arg of 1 for N. 

2. Redefine the functions above and add docstrings.

3a. Redefine the function from # 1a above and add exceptions to check that:
  - a data frame is the type of object being passed into the data arg
  - the exact value being asked to match on exists in the data frame
  - the columns being asked to select on exist in the data frame

3b. Redefine the function from # 1b above and add at least two useful exceptions 

4. Write helper data for each function above that will be useful to write unit tests.

5. Write tests to check that the functions work correctly

6. Write tests to check that the exceptions work correctly

7. Abstract functions to their own file, and tests to their own folder, file and test functions (one test function per function)

**Comment by mgelbart** [comment]
This looks good overall. Some comments/concerns below.

- For the assignment, I would like to see one or more questions where badly designed functions are corrected by the student. @hfboyce we can discuss the details.

For the content, my worry is that there's too much.

- For

> Scoping (e.g., if x is defined outside the function, and then inside the function, which value for x is used) (test via MCQ showing pictures of function and asking what the value of x would be after running the code and inside the function)

and

> function argument ordering and default/optional arguments (how this impacts how you call the function, i.e., how does order of calling arguments influence when you have to provide their names when calling the function)

I would cover these but not go in too much depth

- I don't think it's needed to show them more than one style of docstring
- I am not 100% sold on the need for defensive programming via exceptions or Abstracting functions and tests to other files. These are nice to have, but the opportunity cost is high. My concern is that this is too much technical stuff to learn, and it doesn't leave enough time for the ideas of good function design choices (e.g. does the loop go inside or outside the function, don't hard-code numbers in functions, etc).

To be discussed!

**Comment by mgelbart** [comment]
Per meeting today, let's remove (6), keep (4), but switch the order of (4) and (5) so that the section on unit tests does not emphasize the idea of testing one's own exceptions.
